name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Install Node.js dependencies
      run: npm install

    # Setup Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: python -m pip install -r requirements.txt

    # Run Node.js tests
    - name: Run Node.js tests
      run: npm test

    # Run Python tests
    - name: Run Python tests
      run: python -m unittest discover tests

    # Optional: Docker steps
    - name: Build Docker image
      run: docker build -t my-app .

    - name: Run Docker container
      run: docker run -d -p 80:80 my-app
