name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        options: > 
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
<<<<<<< HEAD
        node-version: '20'
=======
        node-version: '14'
>>>>>>> 927345dff28b9fa03193ce6a1ade92e20cf3f953

    - name: Install Node.js dependencies
      run: npm install

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: python -m pip install -r requirements.txt

    - name: Run Node.js tests
      run: npm test

    - name: Run Python tests
      run: python -m unittest discover tests

    - name: Build Docker image
      run: docker build -t my-app .

    - name: Run Docker container
      run: docker run -d -p 80:80 my-app
